" Vim settings for GUI only

if has("gui_gtk2")
    set guifont=Monospace\ 9,DejaVu\ Sans\ Mono\ 9,Inconsolata\ Medium\ 12
elseif has("gui_macvim")
    set guifont=Inconsolata:h14,Menlo_Regular:h12,Consolas:h13
else
    set guifont=Consolas:h9,Andale_Mono:h8,Courier_New:h8
endif
set lines=56
set columns=120

" For Win32 GUI: remove 't' flag from 'guioptions': no tearoff menu entries
set guioptions-=t

" I can't remember the last time I clicked anything on the toolbar, so just
" turn it off to save space.
set guioptions-=T

" Set personal GUI colors  {{{
if v:version >= 600
  let g:molokai_original = 1
  "colorscheme inkpot
  "colorscheme desert
  set background=light
  colorscheme solarized
endif
" }}}

set number      " show line numbers in GUI mode only
set cursorline  " highlight the current line

" vim600:fdm=marker:fdl=1:
