" Vim settings for all instances

" General options "{{{
set history=50		" keep 50 lines of command line history

behave mswin
"}}}
" Appearance options "{{{
set laststatus=2	" show status line all the time
set ruler		    " show the cursor position all the time
set showcmd		    " display incomplete commands
syntax on           " syntax highlighting
"}}}
" Search options "{{{
set incsearch		" do incremental searching
set hlsearch        " highlight the last used search pattern

" Use GNU grep instead of findstr for the :grep command
set grepprg=grep\ -nH
"}}}
" File handling options "{{{
set nobackup		" do not keep a backup file

" Enable file type detection.
filetype on
" Also load indent files, to automatically do language-dependent indenting.
if v:version >= 600
  filetype plugin indent on
endif
"}}}

" Default file options "{{{
" (these can be overridden later for specific filetypes)
set autoindent		" always set autoindenting on
set tabstop=4       " I almost always use 4-space tabs
set softtabstop=4
set shiftwidth=4
set expandtab
"}}}

" Keyboard mappings and behavior "{{{
" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Don't use Ex mode, use Q for formatting
map Q gq
"}}}

" For all text files set 'textwidth' to 78 characters.
autocmd FileType text setlocal textwidth=78

" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid or when inside an event handler
" (happens when dropping a file on gvim).
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

" vim:foldmethod=marker:foldlevel=0
