" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set autoindent		" always set autoindenting on
set nobackup		" do not keep a backup file
set history=50		" keep 50 lines of command line history
set laststatus=2	" show status line all the time
set ruler		    " show the cursor position all the time
set showcmd		    " display incomplete commands
set incsearch		" do incremental searching

" Use GNU grep instead of findstr for the :grep command
set grepprg=grep\ -nH

" Don't use Ex mode, use Q for formatting
map Q gq

syntax on               " syntax highlighting
set hlsearch            " highlight the last used search pattern

" Enable file type detection.
filetype on
" Also load indent files, to automatically do language-dependent indenting.
if v:version >= 600
  filetype plugin indent on
endif

" For all text files set 'textwidth' to 78 characters.
autocmd FileType text setlocal textwidth=78

" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid or when inside an event handler
" (happens when dropping a file on gvim).
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

behave mswin
