#!/bin/sh

echo "Installing rust..."
rustup-init -y --no-modify-path > /dev/null
# Make sure `cargo` is in $PATH
source $HOME/.cargo/env
rustup component add clippy

# for `cargo add`
cargo install edit
