#!/bin/bash
set -e

# Load rbenv in case it's the first time installing
eval "$(rbenv init -)"

latest_ruby_version(){
  rbenv install -l 2>/dev/null | rg '^\d' | tail -1
}

echo "Installing latest Ruby (version $(latest_ruby_version))..."
if rbenv versions | rg "$(latest_ruby_version)" > /dev/null; then
  echo "Already installed"
else
  rbenv install "$(latest_ruby_version)"
  rbenv global "$(latest_ruby_version)"
fi
