[directory]
style = "fg:031"
# Show 2 full parent directories (setting to 0 means no truncation)
truncation_length = 3
# truncation_symbol = "…/"
# Replace shortened dirs with first character
fish_style_pwd_dir_length = 1
# When in a Git repo, keep showing parent directories
truncate_to_repo = false
repo_root_style = "bold fg:039"

[git_branch]
only_attached = true

[git_commit]
format = "at [($tag )](bold purple)[\\($hash\\)]($style) "
commit_hash_length = 8
tag_disabled = false
tag_symbol = "#"
style = "fg:245" # medium gray

[git_status]
format = '([\[$conflicted$deleted$renamed$modified$staged$untracked\]]($style) )[($ahead_behind$stashed )](cyan)'
conflicted = "~"
stashed = "≡"
diverged = "⇡⇣"

[c]
# C/C++ version detection is too slow
disabled = true

[aws]
disabled = true
